-- ============================================================================
-- COMPLIANCE Q&A: Additional Verified Entries
-- ============================================================================
-- FMCSA and Washington UTC requirements for passenger carriers
-- All citations verified against official regulations
-- ============================================================================

INSERT INTO compliance_qa (
    canonical_question,
    question_variations,
    answer_text,
    answer_summary,
    primary_citation,
    citation_url,
    category,
    carrier_types,
    jurisdiction,
    applies_to_interstate,
    applies_to_intrastate,
    passenger_capacity_min,
    verified_by,
    verified_at,
    is_current,
    is_active
) VALUES

-- DRIVER QUALIFICATION ENTRIES
(
    'What are the Hours of Service (HOS) limits for passenger-carrying drivers?',
    ARRAY['How many hours can a bus driver work?', 'What is the driving limit for charter bus drivers?', 'HOS rules for passenger carriers'],
    'Passenger-carrying CMV drivers are limited to: (1) 10 hours maximum driving time after 8 consecutive hours off duty; (2) No driving after being on duty 15 hours following 8 consecutive hours off duty; (3) No driving after 60 hours on duty in 7 consecutive days OR 70 hours in 8 consecutive days. Drivers must take at least 8 consecutive hours off duty before restarting driving time. Unlike property-carrying drivers, passenger carriers do NOT have a 30-minute break requirement or use of the sleeper berth exception.',
    '10 hours max driving, 15 hours on-duty limit, 60/7 or 70/8 cycle',
    '49 CFR 395.5',
    'https://www.ecfr.gov/current/title-49/section-395.5',
    'HOS',
    ARRAY['passenger'],
    'Federal',
    true,
    false,
    16,
    'regulatory_review',
    NOW(),
    true,
    true
),
(
    'What pre-trip inspection is required before each trip?',
    ARRAY['What should drivers check before starting a trip?', 'Daily vehicle inspection requirements', 'Pre-trip checklist items'],
    'Before driving a CMV, the driver must be satisfied that the following parts and accessories are in good working order: service brakes, parking brake, steering mechanism, lighting devices and reflectors, tires, horn, windshield wipers, rear-vision mirrors, coupling devices, wheels and rims, and emergency equipment. The driver must review the last driver vehicle inspection report (DVIR) if one was prepared. If defects were reported, the motor carrier must certify that repairs were made or unnecessary before the vehicle is operated. This inspection should be documented.',
    'Check brakes, steering, lights, tires, horn, wipers, mirrors, coupling, wheels, emergency equipment; review last DVIR',
    '49 CFR 392.7, 396.13',
    'https://www.ecfr.gov/current/title-49/section-392.7',
    'DRIVER_QUAL',
    ARRAY['passenger', 'property'],
    'Federal',
    true,
    true,
    null,
    'regulatory_review',
    NOW(),
    true,
    true
),
(
    'What is the minimum age requirement to operate a commercial passenger vehicle?',
    ARRAY['How old do you have to be to drive a charter bus?', 'Age requirement for CMV drivers', 'CDL age limit'],
    'For interstate commerce: The minimum age is 21 years old (49 CFR 391.11). For intrastate commerce in Washington State: The minimum age is 18 years old with a valid CDL, though many motor carriers set their own higher age requirements for insurance purposes. Note that drivers under 21 may not transport passengers in interstate commerce under any circumstances.',
    '21 years for interstate; 18 years for intrastate (WA)',
    '49 CFR 391.11(b)(1)',
    'https://www.ecfr.gov/current/title-49/section-391.11',
    'DRIVER_QUAL',
    ARRAY['passenger'],
    'Federal',
    true,
    false,
    null,
    'regulatory_review',
    NOW(),
    true,
    true
),
(
    'What drug and alcohol testing is required for CDL drivers?',
    ARRAY['When are drug tests required?', 'DOT drug testing requirements', 'Random drug testing frequency'],
    'CDL drivers must undergo: (1) Pre-employment drug testing before first performing safety-sensitive functions; (2) Random testing - minimum 25% of drivers for drug testing and 10% for alcohol testing annually; (3) Post-accident testing when the driver receives a citation and there is a fatality, bodily injury requiring immediate medical treatment, or disabling vehicle damage; (4) Reasonable suspicion testing when a trained supervisor observes signs of drug or alcohol use; (5) Return-to-duty and follow-up testing after any violation. All testing must use DOT-approved methods and laboratories.',
    'Pre-employment, random (25% drug/10% alcohol), post-accident, reasonable suspicion, return-to-duty',
    '49 CFR Part 382',
    'https://www.ecfr.gov/current/title-49/part-382',
    'DRUG_ALCOHOL',
    ARRAY['passenger', 'property'],
    'Federal',
    true,
    true,
    null,
    'regulatory_review',
    NOW(),
    true,
    true
),

-- VEHICLE REQUIREMENTS
(
    'What emergency equipment must be carried on a passenger vehicle?',
    ARRAY['What safety equipment is required on a bus?', 'Emergency supplies for charter vehicles', 'First aid kit requirements'],
    'Each bus must be equipped with: (1) At least one fire extinguisher with at least 5 B:C rating, properly mounted, charged, and readily accessible; (2) Emergency reflective triangles (3 units); (3) Spare electrical fuses (if equipped with fusible circuits); (4) First aid kit is NOT federally required but highly recommended and may be required by state law or contract. Washington State requires buses to carry emergency equipment including flares or reflective triangles and a fire extinguisher.',
    'Fire extinguisher (5 B:C minimum), reflective triangles (3), spare fuses; first aid kit recommended',
    '49 CFR 393.95',
    'https://www.ecfr.gov/current/title-49/section-393.95',
    'VEHICLE',
    ARRAY['passenger'],
    'Federal',
    true,
    true,
    null,
    'regulatory_review',
    NOW(),
    true,
    true
),
(
    'How often must commercial vehicle brakes be inspected?',
    ARRAY['Brake inspection frequency', 'When do brakes need to be checked?', 'Commercial vehicle brake requirements'],
    'Vehicle brakes must be inspected at multiple intervals: (1) Driver pre-trip inspection before each trip; (2) During the annual vehicle inspection; (3) Any time the driver has reason to believe the brakes are not functioning properly. For vehicles requiring periodic inspection, brake components including linings, drums, rotors, hose, tubing, and connections must be inspected and documented. Brake adjustment must be checked and brakes must be properly adjusted at all times. The pushrod travel should not exceed adjustment limits specified in the brake manufacturer documentation.',
    'Pre-trip daily, during annual inspection, and whenever suspected issues',
    '49 CFR 396.3, 396.17, 393.47',
    'https://www.ecfr.gov/current/title-49/section-393.47',
    'VEHICLE',
    ARRAY['passenger', 'property'],
    'Federal',
    true,
    true,
    null,
    'regulatory_review',
    NOW(),
    true,
    true
),
(
    'What are the requirements for maintaining a Driver Vehicle Inspection Report (DVIR)?',
    ARRAY['Do I need to complete a DVIR?', 'Post-trip inspection paperwork', 'Vehicle inspection report requirements'],
    'At the completion of each day''s work on each vehicle operated, the driver must prepare a written report (DVIR) covering at minimum: service brakes, parking brake, steering mechanism, lighting devices and reflectors, tires, horn, windshield wipers, rear-vision mirrors, coupling devices, wheels and rims, and emergency equipment. If no defects are found, the carrier may use a simplified certification. The motor carrier must retain the original for 3 months from the date of receipt. The carrier must repair any defects or deficiencies that would affect safe operation before the vehicle is dispatched.',
    'Prepare DVIR at end of each day covering 11 specific items; retain for 3 months; repair before dispatch',
    '49 CFR 396.11, 396.13',
    'https://www.ecfr.gov/current/title-49/section-396.11',
    'VEHICLE',
    ARRAY['passenger', 'property'],
    'Federal',
    true,
    true,
    null,
    'regulatory_review',
    NOW(),
    true,
    true
),
(
    'What tire requirements apply to passenger-carrying vehicles?',
    ARRAY['Tire depth requirements for buses', 'Commercial vehicle tire regulations', 'When must tires be replaced?'],
    'Tires on CMVs must meet these requirements: (1) No tire may have body ply or belt material exposed; (2) No flat tires or audible air leaks; (3) Steer axle tires must have at least 4/32 inch tread depth; (4) All other axle tires must have at least 2/32 inch tread depth; (5) No re-grooved tires on steer axles of buses; (6) Tires must be properly inflated for the load; (7) Tires must not have defects that could cause sudden failure. Regular inspections should verify proper inflation, tread depth, and check for cuts, abrasions, bulges, or separation.',
    'Steer tires: 4/32" minimum; other axles: 2/32" minimum; no exposed cords, proper inflation required',
    '49 CFR 393.75',
    'https://www.ecfr.gov/current/title-49/section-393.75',
    'VEHICLE',
    ARRAY['passenger', 'property'],
    'Federal',
    true,
    true,
    null,
    'regulatory_review',
    NOW(),
    true,
    true
),

-- RECORD KEEPING
(
    'How long must driver qualification files be retained?',
    ARRAY['DQ file retention period', 'How long to keep driver records?', 'Driver file documentation requirements'],
    'A motor carrier must maintain a driver qualification file for each driver employed. The file must include: application for employment, motor vehicle record (MVR), medical examiner''s certificate, road test form or equivalent, annual review of driving record, and other required documents. Files must be retained for the duration of employment plus 3 years after the driver leaves employment. Specific documents like the medical certificate must be updated and current throughout employment. Investigation records must be retained as part of the file.',
    'Employment duration plus 3 years after separation',
    '49 CFR 391.51',
    'https://www.ecfr.gov/current/title-49/section-391.51',
    'DRIVER_QUAL',
    ARRAY['passenger', 'property'],
    'Federal',
    true,
    true,
    null,
    'regulatory_review',
    NOW(),
    true,
    true
),
(
    'What records must be kept for drug and alcohol testing?',
    ARRAY['Drug test record retention', 'How long to keep DOT drug test results?', 'Testing documentation requirements'],
    'Drug and alcohol testing records must be retained as follows: (1) Records of verified positive results, refusals, and associated documents - 5 years; (2) Records of negative and cancelled test results - 1 year; (3) Alcohol test results of 0.02 or greater - 5 years; (4) Training records for supervisors - indefinitely while supervisor is employed; (5) Random selection records - 2 years; (6) Consortium agreements - as long as applicable plus 5 years. All records must be stored securely with access limited to authorized personnel.',
    'Positives and refusals: 5 years; negatives: 1 year; random selection: 2 years',
    '49 CFR 382.401',
    'https://www.ecfr.gov/current/title-49/section-382.401',
    'DRUG_ALCOHOL',
    ARRAY['passenger', 'property'],
    'Federal',
    true,
    true,
    null,
    'regulatory_review',
    NOW(),
    true,
    true
),

-- WASHINGTON UTC SPECIFIC
(
    'What is required for Washington State passenger carrier operating authority?',
    ARRAY['How do I get WA charter authority?', 'UTC permit requirements', 'Washington state bus permit'],
    'To operate as a passenger carrier in Washington State, you must obtain a certificate of public convenience and necessity from the Washington Utilities and Transportation Commission (UTC). Requirements include: (1) Application form with proposed services; (2) Evidence of financial responsibility (insurance); (3) Filing fee; (4) Background investigation; (5) Safety fitness determination. Charter and excursion carriers must demonstrate they meet safety standards. The certificate must be renewed and carriers must file annual reports. Some exemptions exist for school buses, government-operated vehicles, and vehicles seating fewer than 8 passengers including the driver operating solely within one city.',
    'UTC certificate required; includes application, insurance proof, fees, background check, safety review',
    'RCW 81.68.040',
    'https://app.leg.wa.gov/RCW/default.aspx?cite=81.68.040',
    'AUTHORITY',
    ARRAY['passenger'],
    'Washington',
    false,
    true,
    null,
    'regulatory_review',
    NOW(),
    true,
    true
),
(
    'What insurance requirements apply to passenger carriers in Washington?',
    ARRAY['Bus insurance requirements WA', 'Liability coverage for charter buses', 'Washington state insurance minimums'],
    'Washington passenger carriers must maintain public liability and property damage insurance. The minimum requirements are: (1) Vehicles seating 8-15 passengers: $1,500,000 combined single limit; (2) Vehicles seating 16-30 passengers: $5,000,000 combined single limit; (3) Vehicles seating more than 30 passengers: $5,000,000 combined single limit. For interstate carriers, FMCSA requires a minimum of $5,000,000 for vehicles designed or used to transport 16 or more passengers. Proof of insurance must be filed with the UTC and carriers must maintain insurance at all times. Lapses in coverage can result in suspension of operating authority.',
    'WA: $1.5M (8-15 pax), $5M (16+ pax); Interstate: $5M (16+ pax)',
    'WAC 480-30-221',
    'https://apps.leg.wa.gov/wac/default.aspx?cite=480-30-221',
    'AUTHORITY',
    ARRAY['passenger'],
    'Washington',
    false,
    true,
    8,
    'regulatory_review',
    NOW(),
    true,
    true
),

-- SAFETY & OPERATIONS
(
    'What are the requirements for passenger seatbelts?',
    ARRAY['Do buses need seatbelts?', 'Seatbelt requirements for charter vehicles', 'Passenger restraint systems'],
    'Federal requirements for passenger seatbelts depend on vehicle type and manufacture date: (1) Over-the-road buses (designed for long-distance travel) manufactured after November 28, 2016 must have 3-point seatbelts at all designated seating positions; (2) Large buses (GVWR over 26,000 lbs) manufactured after October 21, 2011 for interstate commerce must have seatbelts installed; (3) Smaller vehicles (under 10,000 lbs GVWR) must have occupant protection meeting FMVSS 208. When seatbelts are installed, passengers should be instructed on their use. Washington State follows federal requirements and may require additional safety equipment.',
    'Over-the-road buses after Nov 2016 need 3-point belts; varies by vehicle type and date',
    '49 CFR 571.208, 571.210',
    'https://www.ecfr.gov/current/title-49/section-571.208',
    'VEHICLE',
    ARRAY['passenger'],
    'Federal',
    true,
    true,
    null,
    'regulatory_review',
    NOW(),
    true,
    true
),
(
    'What are the cell phone and texting rules for commercial drivers?',
    ARRAY['Can CDL drivers use cell phones?', 'Texting while driving commercial vehicle', 'Mobile phone restrictions for bus drivers'],
    'Commercial drivers are prohibited from: (1) Using a hand-held mobile telephone while driving a CMV - drivers may use a hands-free phone if the device is located in close proximity, the driver uses earpiece or speaker, and can initiate/terminate calls with single button push; (2) Texting while driving - this includes reading, writing, or sending SMS messages, email, instant messages, or accessing internet pages. Violations can result in driver disqualification (60 days for second offense, 120 days for third) and fines. Carriers are prohibited from requiring or allowing drivers to use hand-held phones while driving. Use of a CMV while using a hand-held phone is a serious traffic violation.',
    'No hand-held phones, no texting while driving; hands-free permitted; violations cause disqualification',
    '49 CFR 392.82',
    'https://www.ecfr.gov/current/title-49/section-392.82',
    'DRIVER_QUAL',
    ARRAY['passenger', 'property'],
    'Federal',
    true,
    true,
    null,
    'regulatory_review',
    NOW(),
    true,
    true
),
(
    'What smoking and eating rules apply while operating a passenger vehicle?',
    ARRAY['Can drivers smoke while driving passengers?', 'Eating while driving bus', 'Driver conduct rules'],
    'FMCSA regulations do not specifically prohibit smoking or eating while driving, however many carriers establish these as company policies. Washington State law (RCW 70.160.075) prohibits smoking in motor vehicles when a minor child is present and prohibits smoking on public transit. For passenger comfort and safety, most charter companies prohibit drivers from smoking in vehicles at any time. Eating while driving can be considered a distraction and should be avoided. Many insurance policies and company safety programs explicitly prohibit these activities while the vehicle is in motion with passengers aboard.',
    'No federal ban, but WA prohibits smoking with minors; most carriers prohibit as policy',
    'RCW 70.160.075',
    'https://app.leg.wa.gov/RCW/default.aspx?cite=70.160.075',
    'DRIVER_QUAL',
    ARRAY['passenger'],
    'Washington',
    false,
    true,
    null,
    'regulatory_review',
    NOW(),
    true,
    true
),
(
    'What are the alcohol and drug use prohibitions for drivers?',
    ARRAY['When can a driver drink alcohol?', 'Driver alcohol rules', 'Pre-duty alcohol restrictions'],
    'A driver is prohibited from: (1) Using or being under the influence of any controlled substance (except as prescribed by a physician who has advised the driver it will not affect driving); (2) Having ANY measurable alcohol concentration (0.00 BAC) while on duty or operating a CMV; (3) Being under the influence of alcohol (as defined by state law) within 4 hours before going on duty; (4) Using alcohol while performing safety-sensitive functions; (5) Using alcohol within 8 hours after an accident OR until post-accident testing is complete. A driver testing 0.02-0.039 BAC must be removed from safety-sensitive functions for 24 hours. Testing 0.04 or higher is a positive result requiring SAP evaluation.',
    'Zero tolerance on duty; no alcohol 4 hours before duty; 8 hours after accident; 0.04 is positive',
    '49 CFR 392.4, 392.5, 382.201-215',
    'https://www.ecfr.gov/current/title-49/section-392.5',
    'DRUG_ALCOHOL',
    ARRAY['passenger', 'property'],
    'Federal',
    true,
    true,
    null,
    'regulatory_review',
    NOW(),
    true,
    true
),
(
    'What DOT number and marking requirements apply to passenger vehicles?',
    ARRAY['Do buses need DOT numbers?', 'Vehicle marking requirements', 'USDOT number display'],
    'Carriers operating CMVs in interstate commerce must obtain a USDOT number and display it on both sides of each power unit. Display requirements: (1) Contrasting color to vehicle; (2) Letters at least 2 inches high; (3) Legible during daylight from 50 feet; (4) Must include legal name or single trade name and USDOT number preceded by "USDOT". Washington intrastate carriers must display their UTC permit number. Markings must be maintained in readable condition. Operating authority numbers (MC numbers for interstate passenger carriers) do not need to be displayed on the vehicle but the USDOT number is required.',
    'USDOT number on both sides, 2" letters minimum, contrasting color, legal name or trade name',
    '49 CFR 390.21',
    'https://www.ecfr.gov/current/title-49/section-390.21',
    'AUTHORITY',
    ARRAY['passenger', 'property'],
    'Federal',
    true,
    false,
    null,
    'regulatory_review',
    NOW(),
    true,
    true
)

ON CONFLICT (canonical_question) DO UPDATE SET
    answer_text = EXCLUDED.answer_text,
    answer_summary = EXCLUDED.answer_summary,
    primary_citation = EXCLUDED.primary_citation,
    updated_at = NOW();

-- Add comments
COMMENT ON TABLE compliance_qa IS 'Verified compliance Q&A entries for FMCSA and Washington UTC regulations - for passenger carrier operations';
