/**
 * GPT Store API: Create Booking Inquiry
 *
 * Allows ChatGPT to submit booking inquiries on behalf of users
 * Creates a pending inquiry that the Walla Walla Travel team will follow up on
 */

import { NextRequest, NextResponse } from 'next/server';
import { query } from '@/lib/db-helpers';
import { z } from 'zod';
import { logger } from '@/lib/logger';

// CORS headers for ChatGPT
const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization'
};

// Validation schema
const InquirySchema = z.object({
  name: z.string().min(2, 'Name must be at least 2 characters'),
  email: z.string().email('Please provide a valid email address'),
  phone: z.string().optional(),
  tour_date: z.string().refine((date) => {
    const parsed = new Date(date);
    return !isNaN(parsed.getTime());
  }, 'Please provide a valid date in YYYY-MM-DD format'),
  party_size: z.number().int().min(1).max(14),
  tour_type: z.enum(['wine_tour', 'private_transportation', 'corporate', 'bachelorette']).optional().default('wine_tour'),
  preferences: z.string().optional(),
  pickup_location: z.string().optional(),
  // Optional fields for ChatGPT integration
  brand: z.enum(['wwt', 'nwtc', 'hcwt']).optional().default('wwt'),
  session_id: z.string().optional()
});

export async function POST(request: NextRequest) {
  try {
    let body = await request.json();

    // Handle case where body is a string (can happen in test environments)
    if (typeof body === 'string') {
      body = JSON.parse(body);
    }

    // Validate input
    const validation = InquirySchema.safeParse(body);
    if (!validation.success) {
      const errors = validation.error.issues.map(e => e.message).join('. ');
      return NextResponse.json(
        {
          success: false,
          message: `Please provide the required information: ${errors}`,
          inquiry_id: null
        },
        { status: 400, headers: corsHeaders }
      );
    }

    const data = validation.data;

    // Validate date is in the future
    const tourDate = new Date(data.tour_date);
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    if (tourDate < today) {
      return NextResponse.json(
        {
          success: false,
          message: 'The tour date must be in the future. Please choose an upcoming date.',
          inquiry_id: null
        },
        { status: 400, headers: corsHeaders }
      );
    }

    // Check minimum lead time (3 days for wine tours)
    const minLeadDays = 3;
    const leadTime = Math.floor((tourDate.getTime() - today.getTime()) / (1000 * 60 * 60 * 24));
    if (leadTime < minLeadDays) {
      const minDate = new Date(today);
      minDate.setDate(minDate.getDate() + minLeadDays);
      return NextResponse.json(
        {
          success: false,
          message: `We need at least ${minLeadDays} days advance notice for bookings. The earliest available date is ${minDate.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' })}.`,
          inquiry_id: null
        },
        { status: 400, headers: corsHeaders }
      );
    }

    // Format tour type for display
    const tourTypeLabels: Record<string, string> = {
      wine_tour: 'Wine Tour',
      private_transportation: 'Private Transportation',
      corporate: 'Corporate Event',
      bachelorette: 'Celebration/Bachelorette'
    };

    // Map tour_type to experience_type and occasion
    const experienceType = data.tour_type === 'private_transportation' ? 'private_tasting' :
                           data.tour_type === 'corporate' ? 'corporate' : 'wine_tour';
    const occasion = data.tour_type === 'bachelorette' ? 'friends_trip' :
                     data.tour_type === 'corporate' ? 'corporate' : null;

    // Combine preferences and pickup location into special_requests
    const specialRequests = [
      data.preferences,
      data.pickup_location ? `Pickup location: ${data.pickup_location}` : null
    ].filter(Boolean).join('\n') || null;

    // Create the inquiry in experience_requests table
    // The request_number is auto-generated by database trigger (EXP-YYYY-NNNN format)
    const result = await query<{ request_number: string }>(
      `INSERT INTO experience_requests
       (contact_name, contact_email, contact_phone, party_size, preferred_date,
        experience_type, special_requests, occasion, brand, source, source_session_id, status)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'chatgpt', $10, 'new')
       RETURNING request_number`,
      [
        data.name,
        data.email,
        data.phone || null,
        data.party_size,
        data.tour_date,
        experienceType,
        specialRequests,
        occasion,
        data.brand || 'wwt',
        data.session_id || null
      ]
    );

    const inquiryId = result.rows[0]?.request_number || `EXP-${Date.now()}`;

    // Format confirmation message
    const formattedDate = tourDate.toLocaleDateString('en-US', {
      weekday: 'long',
      year: 'numeric',
      month: 'long',
      day: 'numeric'
    });

    const message = `Thank you, ${data.name}! Your ${tourTypeLabels[data.tour_type]} inquiry for ${data.party_size} ${data.party_size === 1 ? 'guest' : 'guests'} on ${formattedDate} has been submitted. ` +
      `Your inquiry reference is ${inquiryId}. ` +
      `The Walla Walla Travel team will review your request and respond to ${data.email} within 24 hours with availability and pricing.`;

    return NextResponse.json(
      {
        success: true,
        message,
        inquiry_id: inquiryId,
        estimated_response_time: '24 hours',
        next_steps: [
          `Check your email (${data.email}) for confirmation`,
          'Our team will follow up with availability and pricing details',
          'You can reply to the email with any questions'
        ]
      },
      { status: 201, headers: corsHeaders }
    );
  } catch (error) {
    logger.error('GPT create-inquiry error', { error });
    return NextResponse.json(
      {
        success: false,
        message: 'Unable to submit your inquiry at this time. Please try again or contact us directly at info@wallawalla.travel or (509) 555-WINE.',
        inquiry_id: null
      },
      { status: 500, headers: corsHeaders }
    );
  }
}

export async function OPTIONS() {
  return new NextResponse(null, {
    status: 200,
    headers: corsHeaders
  });
}
