#!/bin/bash
# Morning Briefing — Daily summary of automated issues
# Creates a GitHub issue with a digest of open sentry-error, ci-failure,
# review-due, and health-check issues.
#
# Usage: bash scripts/morning-briefing.sh
# Requires: gh CLI (available on GitHub Actions runners)

set -euo pipefail

# ── Configuration ─────────────────────────────────────────────────────────

LABELS="sentry-error,ci-failure,review-due,health-check"
BRIEFING_LABEL="daily-briefing"
DATE=$(date -u +"%Y-%m-%d")

# ── Helpers ───────────────────────────────────────────────────────────────

print_header() {
  echo ""
  echo "============================================"
  echo "  $1"
  echo "============================================"
}

# ── Collect issues by label ───────────────────────────────────────────────

BODY=""
TOTAL=0

for LABEL in ${LABELS//,/ }; do
  COUNT=$(gh issue list --label "$LABEL" --state open --json number --jq 'length' 2>/dev/null || echo "0")
  TOTAL=$((TOTAL + COUNT))

  if [ "$COUNT" -gt 0 ]; then
    BODY="${BODY}### ${LABEL} (${COUNT} open)"$'\n\n'

    ISSUES=$(gh issue list --label "$LABEL" --state open --json number,title,createdAt \
      --jq '.[] | "- #\(.number) \(.title) _(opened \(.createdAt | split("T")[0]))_"' 2>/dev/null || echo "")

    BODY="${BODY}${ISSUES}"$'\n\n'
  fi
done

# ── Build briefing ────────────────────────────────────────────────────────

if [ "$TOTAL" -eq 0 ]; then
  SUMMARY="All clear — no automated issues open."
  BODY="No open issues with labels: ${LABELS}."$'\n\n'"Nothing requires attention today."
else
  SUMMARY="${TOTAL} open issue(s) across automated labels."
fi

FULL_BODY="## Morning Briefing — ${DATE}"$'\n\n'
FULL_BODY="${FULL_BODY}**Summary:** ${SUMMARY}"$'\n\n'
FULL_BODY="${FULL_BODY}${BODY}"
FULL_BODY="${FULL_BODY}---"$'\n'
FULL_BODY="${FULL_BODY}*Auto-generated by morning briefing workflow*"

# ── Close previous briefing ───────────────────────────────────────────────

print_header "Closing previous briefing issues"

PREV_ISSUES=$(gh issue list --label "$BRIEFING_LABEL" --state open --json number --jq '.[].number' 2>/dev/null || echo "")

for NUM in $PREV_ISSUES; do
  echo "  Closing #${NUM}"
  gh issue close "$NUM" --comment "Superseded by today's briefing." 2>/dev/null || true
done

# ── Create today's briefing ───────────────────────────────────────────────

print_header "Creating briefing for ${DATE}"

gh issue create \
  --title "Morning Briefing — ${DATE}" \
  --body "$FULL_BODY" \
  --label "$BRIEFING_LABEL"

echo ""
echo "Briefing created successfully."
